Fish rendering fix
vr4vet/Blue-Sector pull request #220
Opened 2023-10-16 14:56 UTC by eamathie

* **What kind of change does this PR introduce?**
This is includes a fix to make fish render even when at the bottom of the fish cage. It also fixes the bug where a camera can leave its cage if it's switched to two or more times. Bloom is also enabled, but can easily be disabled again if the performance cost is too great.

* **What is the current behavior?**
Sometimes fish do not render if the cage camera looks upwards from the bottom of the cage. This is mainly caused by the fish' culling distance being set too low in the prefab's LoD settings. See issue #205.  It will naturally also happen if the camera is positioned outside of the cage, which is possible because of an unmentioned bug in the camera control's code.

* **What is the new behavior?**
Fish LoD is adjusted so fish is rendered even when looking upwards from the bottom of the cage. The bug that makes it possible for the camera to move outside of its fish cage is also fixed, preventing this problem from occurring, and also making the camera behave as intended. 

* **Does this PR introduce a breaking change?**
No, it should not break anything, but it contains changes to the scene.

2023-10-17 08:51 UTC, ingolvjr requested changes
I'm getting merge conflicts in fishfeeding.unity scene, probably because of #218

2023-10-17 10:21 UTC, eamathie commented
Merge conflicts in fishfeeding.unity scene should be fixed now

2023-10-17 10:51 UTC, ingolvjr approved these changes
Yep, everything works like it should

2023-10-18 07:41 UTC, SnorreForbregd approved these changes

2023-10-20 09:57 UTC, merged