Fix: ControlBarrier rotates within LocalSpace
vr4vet/Blue-Sector pull request #392
Opened 2024-04-16 15:19 UTC by MarkusJohansen

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The PR fixes a bug where the controlled barrier for switching between conveyour lanes, always rotated towards 45 degrees in worldspace instead of localspace. To ensure flexibility to the prefab, this has been changed to localspace, you can also reverse it, set the speed and set the amount of degrees you want to rotate towards.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Changes is made in the QA scene. It is also worth noting that the physics of the barrier collision is a bit buggy, and one a rare occation force is applied to fish in a direction that launches the fish in the air.

2024-04-16 16:02 UTC, jonp-h requested changes
Did prettier stop working? Else good to merge

2024-04-16 16:02 UTC, jonp-h commented on Assets/FishFactory/BarrierFishHandling.cs
> +    [SerializeField] float slideForce = 10f; // You can adjust this value to get the desired sliding effect
Serialized should be above with prettier?

2024-04-16 16:05 UTC, jonp-h commented
If a wall is moved to make the fish change conveyor belt, perhaps a lever instead of a button would be more logical? A button would make more sense for a hammer.

2024-04-17 06:07 UTC, MarkusJohansen commented
> If a wall is moved to make the fish change conveyor belt, perhaps a lever instead of a button would be more logical? A button would make more sense for a hammer.

Sounds reasonable, however we should adress this when we find out wether we actually need something like a "hammer" to guide the fish to the correct path.

2024-04-17 06:34 UTC, merged