Develop2 to develop
vr4vet/Blue-Sector pull request #565
Opened 2024-07-12 13:56 UTC by Herman1412

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
merge

* **What is the current behavior?** (You can also link to an open issue here)
changes in develop2 is not integrated in develop branch

* **What is the new behavior?** (if this is a feature change)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
Work in progress

2024-08-08 13:15 UTC, qlpham231 requested changes
Everything works for the most part with the fish maintenance scene and the new tablet in other scenes. However, the incorrectly gutted fish on the gutting station in QA needs to be more frequent, same with the alive fish in the bleeding scene.
Fish maintenance scene also needs to be baked and teleportation/scene transition between feeding and maintenance should be added.

2024-08-08 13:17 UTC, eamathie requested changes
Everything works as intended, however there are a few issues:
- There are no means of transportation to the maintenance scenario (and vice versa).
- Damaged fish appear very rarely at the gutting station, meaning the player must spend a lot of time correctly sorting five of them due to all the waiting. The player will probably loose interest.
- Alive fish appear very rarely at the bleeding station, meaning the player must spend a lot of time correctly sorting five of them due to all the waiting. The player will probably loose interest.
- Tier 3 fish felt like it appeared very rarely. However, I haven't experienced that before, so maybe it was due to bad rng? This also caused a lot of waiting.

2024-08-13 13:21 UTC, eamathie approved these changes

2024-08-13 14:06 UTC, qlpham231 approved these changes

2024-08-15 09:25 UTC, eamathie approved these changes

2024-08-15 09:42 UTC, merged