Lab condition factor
vr4vet/Blue-Sector pull request #581
Opened 2024-08-13 11:12 UTC by OlaBekkevold

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
NPC gives feedback to player actions and can skip to the next dialogue automatically, can also disable the skip line button in the editor. Added functionality for weighing and measuring the fish and registering condition factor

* **What is the current behavior?** (You can also link to an open issue here)
Player manually has to skip to the next dialogue after completing an instruction. The measuirng tool and calculator have no functionality
#578 

* **What is the new behavior?** (if this is a feature change)
NPC automatically responds to player action and skips to the next dialogue on certain interactions. Can also use tools to weigh, measure and calculate condition factor

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2024-08-13 11:58 UTC, ingolvjr requested changes
when I do fail the task the NPC just says "try again" and refuses to tell me how to do it again

2024-08-13 12:36 UTC, ingolvjr requested changes
the npc dialogue should be more specific on some of these measurements, like how many decimals in the factor and between which points of the fish should be measured

2024-08-20 13:31 UTC, qlpham231 approved these changes

2024-08-20 13:32 UTC, eamathie approved these changes

2024-08-20 13:32 UTC, merged